export const pacienteModel = {
  id: "",
  foto_url: "",
  nome_completo: "",
  sexo: "",
  cpf: "",
  data_nascimento: "",
  num_cns: "",
  nome_responsavel: "",
  contato: "",
  convenio_id: "",
  em_lista_espera: false,
  status_clinico: "Cadastro",
  nivel_suporte: "",
  comorbidades: [],
  logradouro: "",
  numero: "",
  bairro: "",
  cep: "",
  municipio: "",
  estado: "",
  status_cadastro: "Ativo"
};